name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0
